{"index":{"_index":2,"_id":1}}
{"launch_id":1234567892,"launch_name":"Launch with test items with logs","test_item":1,"unique_id":"unique1","test_case_hash":0,"is_auto_analyzed":false,"issue_type":"ti001","log_level":40000,"original_message_lines":3,"original_message_words_number":8,"message":" Message     \n java.lang.reflect.Method.invoke(Method.java:) \n message error caused by exception","is_merged":false,"start_time":"2020-01-15 10:57:43","merged_small_logs":"","detected_message":" Message     \n message error caused by exception","detected_message_with_numbers":" Message  1   \n message error caused by exception","stacktrace":" java.lang.reflect.Method.invoke(Method.java:) ","only_numbers":"1"}
