{
    "2": [{
        "_id": 4,
        "_index": "rp_2",
        "_source": {
            "whole_message": "error occured \r\n error found \r\n error mined",
            "test_item": 2,
            "detected_message": "error occured \r\n error found \r\n error mined",
            "stacktrace": "",
            "launch_id": 1,
            "cluster_id": "0",
            "cluster_message": "",
            "message": "error occured \r\n error found \r\n error mined",
            "log_level": 40000,
            "original_message_lines": 3,
            "original_message_words_number": 6,
            "potential_status_codes": "",
            "found_exceptions": ""
        }
    },
    {
        "_id": 3,
        "_index": "rp_2",
        "_source": {
            "whole_message": "error occured",
            "test_item": 2,
            "detected_message": "error occured",
            "stacktrace": "",
            "launch_id": 1,
            "cluster_id": "0",
            "cluster_message": "",
            "message": "error occured",
            "log_level": 40000,
            "original_message_lines": 1,
            "original_message_words_number": 2,
            "potential_status_codes": "",
            "found_exceptions": ""
        }
    }],
    "5": [{
        "_id": 5,
        "_index": "rp_2",
        "_source": {
            "whole_message": "error occured \r\n error found \r\n error mined",
            "test_item": 5,
            "detected_message": "error occured \r\n error found \r\n error mined",
            "stacktrace": "",
            "launch_id": 1,
            "cluster_id": "0",
            "cluster_message": "",
            "message": "error occured \r\n error found \r\n error mined",
            "log_level": 40000,
            "original_message_lines": 3,
            "original_message_words_number": 6,
            "potential_status_codes": "",
            "found_exceptions": ""
        }
    }],
    "6": [{
        "_id": 9,
        "_index": "rp_2",
        "_source": {
            "whole_message": "error occured \r\n error found \r\n assert query",
            "test_item": 6,
            "detected_message": "error occured \r\n error found \r\n assert query",
            "stacktrace": "",
            "launch_id": 1,
            "cluster_id": "0",
            "cluster_message": "",
            "message": "error occured \r\n error found \r\n assert query",
            "log_level": 40000,
            "original_message_lines": 3,
            "original_message_words_number": 6,
            "potential_status_codes": "",
            "found_exceptions": ""
        }
    }]
}